global:
  scrape_interval: 1s # 默认抓取间隔
  evaluation_interval: 10s # 默认评估间隔

# 规则文件配置
rule_files:
  - "rules/*.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']
  - job_name: 'productdemoaop'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['productdemoaop:8080']
  - job_name: 'node'
    static_configs:
      - targets: ['192.168.0.4:9100', '192.168.0.240:9100','192.168.0.206:9100','192.168.0.18:9100','192.168.0.135:9100']

